In [5]:
import numpy as np
rng = np.random.default_rng()

In [2]:
a = np.arange(1, 11, 1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
b = np.zeros((3, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
c = rng.integers(low=1, high=10, endpoint=True, size=(5, 5))
print(c)

[[ 7  6  9  6  8]
 [10  5  9  4  2]
 [ 3  6  9 10  2]
 [ 8  9  7  9  1]
 [ 7  6 10  9  7]]


In [5]:
d = rng.random((4, 4))
print(d)

[[0.81812486 0.6779126  0.30750874 0.13539748]
 [0.86439589 0.17901306 0.23451701 0.17786441]
 [0.93212696 0.3378096  0.75214223 0.89128444]
 [0.21637508 0.06542817 0.93272422 0.6875785 ]]


In [6]:
e_1 = rng.integers(low=1, high=10, endpoint=True, size=(5))
e_2 = rng.integers(low=1, high=10, endpoint=True, size=(5))
print(e_1, e_2)
add_e = e_1 + e_2
print("Add:", add_e)
sub_e = e_1 - e_2
print("Sub:", sub_e)
mult_e = e_1 * e_2
print("Mult:", mult_e)

[ 7 10  4  1  9] [10  8  2  1  4]
Add: [17 18  6  2 13]
Sub: [-3  2  2  0  5]
Mult: [70 80  8  1 36]


In [7]:
f_1 = np.array([1, 2, 3])
f_2 = np.array([3, 2, 1])
print(np.dot(f_1, f_2))

10


In [8]:
g_1 = rng.integers(low=1, high=10, endpoint=True, size=(2, 2))
g_2 = rng.integers(low=1, high=10, endpoint=True, size=(2, 3))
print(g_1)
print(g_2)
print(np.dot(g_1, g_2))

[[ 9 10]
 [ 7  6]]
[[3 8 7]
 [9 3 2]]
[[117 102  83]
 [ 75  74  61]]


In [12]:
h = rng.integers(low=1, high=10, endpoint=True, size=(3, 3))
h_inv = np.linalg.inv(h)
print(h)
print(h_inv)
print(np.dot(h, h_inv).round(2))

[[2 4 1]
 [1 1 4]
 [9 8 8]]
[[-0.38095238 -0.38095238  0.23809524]
 [ 0.44444444  0.11111111 -0.11111111]
 [-0.01587302  0.31746032 -0.03174603]]
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [10]:
i = rng.random((4, 4))
i_t = i.T
print(i)
print(i_t)

[[0.16272376 0.29196216 0.23829614 0.50913997]
 [0.28064709 0.89784533 0.06007844 0.76606512]
 [0.33582726 0.3312347  0.90213262 0.50483691]
 [0.05848079 0.16313962 0.22387616 0.60633809]]
[[0.16272376 0.28064709 0.33582726 0.05848079]
 [0.29196216 0.89784533 0.3312347  0.16313962]
 [0.23829614 0.06007844 0.90213262 0.22387616]
 [0.50913997 0.76606512 0.50483691 0.60633809]]


In [11]:
j_1 = rng.integers(low=1, high=10, endpoint=True, size=(3, 4))
j_2 = rng.integers(low=1, high=10, endpoint=True, size=(4))
print(j_1)
print(j_2)
print(np.dot(j_1, j_2))

[[ 5  2  2  2]
 [ 7 10  3 10]
 [ 7  6  7  5]]
[4 7 2 7]
[ 52 174 119]


In [12]:
k_1 = rng.random((2, 3))
k_2 = rng.random((3))
print(k_1)
print(k_2)
print(np.dot(k_1, k_2))

[[0.14337827 0.91415616 0.57768203]
 [0.36020144 0.60937124 0.56505575]]
[0.18326841 0.44455911 0.91509987]
[0.96130991 0.85399752]


In [13]:
l_1 = rng.integers(low=1, high=10, endpoint=True, size=(2, 2))
l_2 = rng.integers(low=1, high=10, endpoint=True, size=(2, 2))
print(l_1)
print(l_2)
print(l_1 * l_2)

[[8 1]
 [2 9]]
[[9 5]
 [2 1]]
[[72  5]
 [ 4  9]]


In [14]:
m_1 = rng.integers(low=1, high=10, endpoint=True, size=(2, 2))
m_2 = rng.integers(low=1, high=10, endpoint=True, size=(2, 2))
print(m_1)
print(m_2)
print(np.dot(m_1, m_2))

[[6 3]
 [8 2]]
[[9 2]
 [8 8]]
[[78 36]
 [88 32]]


In [15]:
n = rng.integers(low=1, high=100, endpoint=True, size=(5, 5))
print(n)
print(n.sum())

[[66 62 41 90 64]
 [12 82 59 95 40]
 [ 6 24 56 94 24]
 [46 91 11 45 19]
 [44 96 25 32 60]]
1284


In [17]:
o_1 = rng.integers(low=1, high=10, endpoint=True, size=(2, 2))
o_2 = n = rng.integers(low=1, high=10, endpoint=True, size=(2, 2))
print(o_1)
print(o_2)
print(o_1 - o_2)

[[5 3]
 [7 9]]
[[9 9]
 [5 2]]
[[-4 -6]
 [ 2  7]]


In [29]:
p = rng.random((3,3))
print(p)
res = np.array([sum(p[i]) for i in range(p.shape[0])]).reshape(p.shape[1], 1)
print(res)

[[0.213298   0.88876501 0.38800877]
 [0.31980837 0.99825703 0.66847815]
 [0.65414432 0.77867267 0.33940336]]
[[1.49007178]
 [1.98654354]
 [1.77222035]]


In [37]:
t = rng.integers(low=1, high=10, endpoint=True, size=(3, 4))
print(t)
res_t = t.copy()
for i in range(res_t.shape[0]):
    for j in range(res_t.shape[1]):
        res_t[i][j] = pow(t[i][j], 2)
print(res_t)        

[[ 7  2  7  1]
 [10  1  2  6]
 [ 4  1  3  3]]
[[ 49   4  49   1]
 [100   1   4  36]
 [ 16   1   9   9]]


In [43]:
s = rng.integers(low=1, high=50, endpoint=True, size=(4))
print(s)
res_s = s.copy()
res_s = np.array([pow(res_s[i], 0.5) for i in range(res_s.shape[0])])
print(res_s.round(3))

[29 49 19 34]
[5.385 7.    4.359 5.831]
